version: '3.9'

name: ds-parsing-spring-batch

services:

  db:
    image: postgres:14
    container_name: ds-parsing-spring-batch-db
    # networks:
    #   - my_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s

  minio:
    image: minio/minio:latest
    container_name: ds-parsing-spring-batch-minio
    ports:
      - "9000:9000"   # S3 API
      - "9002:9001"   # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./volumes/minio-data:/data
    command: server /data --console-address ":9001"


# volumes:
#   postgres_db_volume:
  